### ISSUE TITLE
Release Saturn-V 1.0.0

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/saturn-v#9]
This is the tracking issue for the first Saturn-V release.

```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
- [x] Configure LEDs (see https://github.com/greatscottgadgets/apollo/issues/39)
- [ ] https://github.com/greatscottgadgets/saturn-v/issues/11
- [x] On older Cynthion revisions, Saturn-V needs to hold the SIDEBAND PHY in reset.
```

```[tasklist]
### Issues
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/saturn-v/pull/12
```
